Description: "Home Backup"
AWSTemplateFormatVersion: "2010-09-09"

Resources:
  bucket:
    Type: "AWS::S3::Bucket"

  user:
    Type: "AWS::IAM::User"
    Properties:
      Policies:
      - PolicyName: WriteToBackupBucketPolicy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action: s3:*
            Resource:
              - !Sub arn:aws:s3:::${bucket}
              - !Sub arn:aws:s3:::${bucket}/*

  accessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName: !Ref user

Outputs:
  bucketName:
    Value: !Ref bucket
    Description: Name of the S3 for backing up files to
  accessKey:
    Description: Access key Id
    Value: !Ref accessKey
  secretAccessKey:
    Description: Secret access key
    Value: !GetAtt accessKey.SecretAccessKey